[package]
name = "zebra-import"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Zcash Foundation <zebra@zfnd.org>"]

[dependencies]
log = "0.4"
zebra-primitives = { path = "../zebra-primitives" }
zebra-chain = { path = "../zebra-chain" }
zebra-serialization = { path = "../zebra-serialization" }
