language: rust

dist: xenial

branches:
  only:
  - master

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

  fast_finish: true

  include:

  # Use a hardcoded nightly version for fmt, so that changes
  # to rustfmt have to be made explicitly, avoiding random fmt
  # failures if rustfmt updates.
  - rust: nightly-2019-06-30
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check

cache:
  directories:
  - "$HOME/.rustup"
  - "$HOME/.cargo"

script:
- cargo test --all
