language: rust

dist: xenial

branches:
  only:
  - master

rust:
  - stable

matrix:
  allow_failures:
    - rust: nightly

  fast_finish: true

  include:

  - rust: nightly
    before_script:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt --all -- --check

cache:
  directories:
  - "$HOME/.rustup"
  - "$HOME/.cargo"

script:
- cargo check --verbose --all
- cargo test --verbose --all
- cargo build --verbose --all
