language: rust # 'stable' is the default

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/.rustup"
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"

# matrix:
#   fast_finish: true

#   allow_failures:
#     - rust: nightly-2019-06-30

#   include:
#     - rust: nightly-2019-06-30
#       before_script: rustup component add rustfmt-preview
#       script: cargo fmt --all -- --check

jobs:
  include:
    - stage: cargo fetch
      name: "cargo fetch --verbose"
      script: cargo fetch --verbose
    - stage: test and build
      name: "cargo test --all"
      script: cargo test --all
    - stage: test and build
      name: "cargo build --release --all"
      script: cargo build --release --all
