steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'zebrad', '.']
  timeout: 1800s # A half hour max for this step alone.

options:
    machineType: 'N1_HIGHCPU_32'

timeout: 3600s # One hour for all steps.
