name: zebra
version: git
summary: A consensus-compatible Zcash node client written in Rust.
description: |
  Zcash client written in Rust.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

apps:
  zebra:
    command: zebra
    plugs: [home, network, network-bind]

parts:
  zebra:
    source: .
    plugin: rust
    build-packages: [g++]
